language: python
python: '2.7'
install: pip install requests requests_oauthlib httpretty
script: python -m unittest discover -v
deploy:
  provider: pypi
  user: nacx
  password:
    secure: RbC/Ua0tVnt0uJzc7akBU4///L7rxMSTm7HzzfN2Vk1k+Kmv9KZEX4RLvNqCFhlzPHnAxSFPxvr/QURpqVFxlvLVrZ5M1A6LryLXK6ZxpmgIuDEibvcNhhPPCc0Phq12g1owOVFKh9XPUomnYRAUaaCKG+p7N7WopqNH6BnrKlQ=
